name: babybashenv
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - conda-forge::librosa
  - conda-forge::pytorch
  - matplotlib
  - scikit-learn
  - joblib
  - pip
  - numba
  - pyinstaller
  - pip:
      - sounddevice
