name: BabyBash CI

# This workflow is triggered on pushes and pull requests to the repository.
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: ['3.11.5']

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: babybashenv
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false

    - name: Activate Conda Environment (Unix)
      if: runner.os != 'Windows'
      run: echo "source activate babybashenv" >> $GITHUB_ENV

    - name: Activate Conda Environment (Windows)
      if: runner.os == 'Windows'
      run: echo "conda activate babybashenv" >> $GITHUB_ENV

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Tests
      run: |
        pytest tests/
